# Generated by Django 5.2.3 on 2025-06-22 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите полное имя сотрудника', max_length=100, verbose_name='ФИО работника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('phone_number', models.CharField(help_text='Формат: +79991234567 или 89991234567', max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79991234567' или '89991234567'", regex='^(\\+7|8)\\d{10}$')], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
            },
        ),
    ]
